
platforms:
    # definition of the "Goldilocks" platform
    Goldilocks:
        board: 


packages:
    Goldilocks:
    https://raw.githubusercontent.com/feilipu/feilipu.github.io/master/package_goldilocks_index.json


{
  "packages": [
      "maintainer": "Adafruit",
      "platforms": [
        {
          "boards": [
            {
              "name": "Adafruit Flora"
            },
            {
              "name": "Adafruit Gemma 8MHz"
            },
            {
              "name": "Adafruit Bluefruit Micro"
            },
            {
              "name": "Adafruit Feather 32u4"
            },
            {
              "name": "Adafruit Metro"
            },
            {
              "name": "Adafruit Pro Trinket 5V/16MHz (USB)"
            },
            {
              "name": "Adafruit Pro Trinket 3V/12MHz (USB)"
            },
            {
              "name": "Adafruit Pro Trinket 5V/16MHz (FTDI)"
            },
            {
              "name": "Adafruit Pro Trinket 3V/12MHz (FTDI)"
            },
            {
              "name": "Adafruit Trinket 8MHz"
            },
            {
              "name": "Adafruit Trinket 16MHz"
            }
          ],
          "architecture": "avr",
          "checksum": "SHA-256:1cca23e9b254c55c1a3cbe2723f81689968a9aa6d7b8ce7e90d52e5253292271",
          "category": "Adafruit",
          "version": "1.4.12",
          "archiveFileName": "adafruit-avr-1.4.12.tar.bz2",
          "url": "https://adafruit.github.io/arduino-board-index/boards/adafruit-avr-1.4.12.tar.bz2",
          "help": {
            "online": "https://forums.adafruit.com"
          },
          "name": "Adafruit AVR Boards",
          "toolsDependencies": [],
          "size": "647288"
        },
      ]
   ]
}
